### ISSUE TITLE
TypeError on Form Validation Page

### ISSUE THREAD

**Issue by Especially** [puikinsh/gentelella#149]
I've noticed that there is an error with the validator.js script, when integrated, such as on the demo form validation html page, when a user types in the input fields, the console log will log the following error:
`jquery.min.js:3 Uncaught TypeError: ((n.event.special[g.origType] || (intermediate value)).handle || g.handler).apply is not a function`

How do we fix this problem?

**Comment by christianesperar** [comment]
I can't replicate the problem. What browser did you use?

**Comment by christianesperar** [comment]
Is this solve? Please reopen it not.

**Comment by kichawa** [comment]
https://colorlib.com/polygon/gentelella/form_validation.html

type sth in 'name' field for example

**Comment by christianesperar** [comment]
The problem is on the validation package that we use. I updated the package and it seems that they already resolve it.

**Comment by Especially** [comment]
It appears this error still persists on https://colorlib.com/polygon/gentelella/form_validation.html

Google Chrome 51.0.2704.84 m (32 bit)
