### ISSUE TITLE
New update Merge text on demo

### ISSUE THREAD

**Issue by louisdauvois** [puikinsh/gentelella#462]
<<<<<<< HEAD ======= >>>>>>> refs/remotes/puikinsh/Development
https://colorlib.com/polygon/gentelella/form.html

**Comment by AndreiCN** [comment]
Noted.

**Comment by AndreiCN** [comment]
This one is already fixed.

**Comment by bakorer** [comment]
@AndreiCN It seems not fixed. Did you deploy not yet?

https://colorlib.com/polygon/gentelella/form.html

![image](https://cloud.githubusercontent.com/assets/844012/26614844/ac4982e2-45fd-11e7-83cd-bce222b87237.png)

**Comment by AndreiCN** [comment]
Live version is not up to date just yet but that issue was solved a while a go ( download the latest version )
