### ISSUE TITLE
Data-tables : show only 10  entries per page 

### ISSUE THREAD

**Issue by selimgnaoui** [puikinsh/gentelella#610]
File  : tables_dynamic.html . while working on #594, we figured out that the Show-entries disappear from the Datatables when you add the export function . 
therefore the tables will just show 10 entries per page . 

hier is an example : 
![image](https://user-images.githubusercontent.com/8598071/32702197-6d3d1074-c7e3-11e7-8bd0-d92a23f25bf1.png)

hier is an example without the export function : 
![image](https://user-images.githubusercontent.com/8598071/32702209-af30f676-c7e3-11e7-9d23-e0a1237fa4e9.png)

**Comment by William-H-M** [comment]
This is not a bug that's how the [`dom`](https://datatables.net/reference/option/dom) option work if you want to see the lenght filter and the exports options you must set up the `dom` to be something like:

`dom: Blfrtip`

**Comment by selimgnaoui** [comment]
@William-H-M  ,    
dom  should be  'lBfrtip'   , I've already found it on the DataTables Documentation ^^

**Comment by William-H-M** [comment]
@selimgnaoui Yeah that of course depends of the position you want to give it, if first length, as yoy have done, or buttons first, as I have done.

As this is solved please close this issue, thanks.

**Comment by selimgnaoui** [comment]
@William-H-M 
Thank you for your answer  , however I think that  this bug is still not resolved ; 

wihtout rewriting a custom function that mention dom : lBfrtip,  you will be not able to export tables and show more than 10 entries per Page. 
as part of an university project, it would be glad if you let me works on it ^^ 

looking forward to hearing from you

**Comment by William-H-M** [comment]
Hi, as I said before this is not a bug is a feature as this are just example and that's why I directed you to the page, this is just a basic layout as listed bye DataTables, the layouts given here are just layoy for you to be guide on, they are not set on stone.

Now if you want to change you can always make a Pull Request to add more options.
Have a nice weekend :D
